server:
    port: 8088
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: erp
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
mybatis:
  mapper-locations: classpath*:com/sw/erp/*/mapper/*.xml
  type-aliases-package: com.sw.erp.*.model

# 打印sql
logging:
  level:
    com.onepro.custom.mapper: DEBUG




